### ISSUE TITLE
@match wildcards don't work with port numbers in hostname

### ISSUE THREAD

**Issue by bendavis78** [derjanb/tampermonkey#218]
I'm trying to make a userscript that only works with my local development sites which I use on localhost (on various ports). I want this script to work on `http://localhost:*/*` but that pattern won't work in tampermonkey. The only way to get the script to activate is by using `http://*/*`.

**Comment by derjanb** [comment]
```@match``` [1] doesn't allow port specifications [2]. Unfortunately TM doesn't respect this well, what causes something like
```@match http://localhost:8888```
to match only port 8888. This will be fixed at the next TM release. 

Nevertheless, your statement ```:*``` is not working cause TM is filtering the invalid wildcard character.

In order to hot-fix your scripts you can use ```@include``` statements instead.


[1] https://developer.chrome.com/extensions/match_patterns
[2] http://stackoverflow.com/questions/11425591/match-port-in-chrome-extension-pattern

**Comment by jonnytest1** [comment]
this seems to be an issue again :
i have an iframe with localhost:8080 but its getting matched by a script that has localhost:4200/*

**Comment by derjanb** [comment]
`localhost:8080` is matched by a `@match` like this?

```
// @match http://localhost:4200/*`
```

That's OK. Port `4200` is ignored and only the host name is compared. You have to use `@include` to make it work.

**Comment by dannybeckett** [comment]
The problem with `@include` is:

![](https://github.com/user-attachments/assets/27172692-8ca5-470e-8414-50a5938ab159)

**Comment by derjanb** [comment]
This warning is reworked at the BETA version to only warn if a regular expression is used:

![image](https://github.com/user-attachments/assets/6eda0687-f32f-4fb2-a276-d3d1799d4c01)
