### ISSUE TITLE
(FR) disable on this website

### ISSUE THREAD

**Issue by drandreaskrueger** [derjanb/tampermonkey#244]
The message "waiting for extension Tampermonkey ..." is slowing down my Chrome quite a bit recently.

I love Tampermonkey, so uninstalling is no option for me.

I would like to be able to make a black list, for disabling it on certain sites, on which I do not need it anyway. Or the other way around, white listing it for the sites on which I am using it.

Extensions like "ublock", "disconnect", or "adblock plus" have found an IMHO good way for that.

*Thanks a lot for considering this idea.*

And thanks a million for the whole thing. Keep up the good work!

:-)

**Comment by derjanb** [comment]
Have you tried the steps at FAQ entry 401? Do they help?
http://tampermonkey.net/faq.php#Q401

**Comment by drandreaskrueger** [comment]
Thanks for your quick reply.

If not the extension itself, then it looks like the script that is responsible is
https://greasyfork.org/en/scripts/1317-download-youtube-videos-as-mp4

Is it doing what Q401 says?
If not, perhaps that author could improve it - right?

**Comment by derjanb** [comment]
This script does not make heavy use of includes, so I don't think this is the root cause of your issue.

Q401 describes how to blacklist and therefore disable all scripts on certain sites. This was your original request, right? Have you tried it out?

Anbother possibility is a bug at Chrome. There recently was a issue which might be able to make TM slow down your Chrome: https://code.google.com/p/chromium/issues/detail?id=520303

And yet another possibility: it's really caused by TM, but this can't not be changed with the current API Chrome offers to extensions. The solution for this case is issue 63979: https://code.google.com/p/chromium/issues/detail?id=63979

**Comment by drandreaskrueger** [comment]
> Q401 describes how to blacklist and therefore disable all scripts on certain sites. 

Not sure I understand @401 ... how I would do that.
Is that simply a new script that I can include into my Tampermonkey?

Could you give an example how to disable all TM scripts on for example
https://github.com

Thanks.

**Comment by derjanb** [comment]
Sure, just set the ```Config Mode``` to ```Beginner``` or higher
![Config mode](http://tampermonkey.net/images/config_mode.png)

and append the pages to exclude at the ```Blacklisted/Forbidden Pages``` setting
![Blacklisted Pages](http://tampermonkey.net/images/security.png)

So in your case you need to add an entry like: ```*github.com/*```.

**Comment by drandreaskrueger** [comment]
... supercool.  So TM does have a blacklist.
I just hadn't found it because of the "novice" settings.

All sorted.

Thank you very much. Enjoy whatever you do!
