### ISSUE TITLE
tampermonkey installed renewed script won't work

### ISSUE THREAD

**Issue by niclubeva** [derjanb/tampermonkey#251]
I have installed a script in tampermonkey there where a few buggs so I renewed the script and installed the new script.
But the new script won'n work. It seems like tampermonkey remembers the old script.
I have installed the new script on a computer whoch didn't have the old version and it works fine.
Does anyone know how I can resolve this issue on the pc where the old script is already running.

thanks in advance

**Comment by derjanb** [comment]
Tampermonkey should not remember a script silently. Do you see the renamed and the new scripts at the dashboard? Have you disabled the reworked script? Otherwise the renamed script might break the new one.

**Comment by niclubeva** [comment]
hello thank you for your reply. I can see the reworked script and if I start the webpage where we want to use the script you can see the number 1 in the right corner of the tampermonkey icon. 
But the script won't work on the page.
the strang thing is, I have installed it on my pc at home and the script works fine (have to say, I only have used the rewokred script at home) But at work I installed the old script first than the reworked script and it won;t work. 
I am not sure but I don't think I have disabled the reworked script, I will try this tomorrow. Thanks again and I let you know.

**Comment by niclubeva** [comment]
hello i have tried it but no luck

**Comment by derjanb** [comment]
Please check the console output. http://tampermonkey.net/faq#Q600 explains how to view it. Do you see any errors?

**Comment by tomasstorck** [comment]
Considering there has been no feedback for over a month, mind if I follow-up on this issue?


# Problem description

It appears at least user.js files are not automatically reloaded when the original location is updated. Revisiting the installation location will show what seems to be a cached version of the user.js file, even if an update was made on the upstream file and even if the server is offline.

Please note that the update action does seem to work correctly, even if the TM settings page does not always show the updated version until you refresh.


# Related issues

I think this issue is the same or at least related to issue #215. They're both describing what appears to me as caching of user.js files.


# Configuration information

Let me know if you need any more information.

I'm running Chromium 47.0.2526.106 with Tampermonkey 3.12.58 or Tampermonkey BETA 3.13.4981. I'll use BETA unless specified otherwise.
The example.user.js is hosted on a local Python 3 HTTPS server (https://127.0.0.1:5000). 


# Reproducibility

## this issue

With cleared cache, example.user.js not installed:
* Browse to https://127.0.0.1:5000/example.user.js
* Install the userscript
* Using your favourite text editor, change version of the example.user.js file
* Browse to https://127.0.0.1:5000/example.user.js again. Note that the option to reinstall the script is visible. The content of the file is shown; any changes made to the example.user.js file are not shown.

This can be done even when the web server is shut down. TM will still load and offer to reinstall the outdated user.js file, even when the server is no longer online (e.g., other browser).

## issue #215

With cleared cache, example.user.js not installed:
* Browse to https://127.0.0.1:5000/example.user.js
* Install the userscript
* Using your favourite text editor, change version of the example.user.js file
* Clear the browser cache
* Browse to https://127.0.0.1:5000/example.user.js again
* Take server offline
* Browse to https://127.0.0.1:5000/example.user.js again. The cached, up-to-date user.js file is shown. You can now click update.


# Workaround

Clear the Chrome cache (ctrl + shift + del). I selected cached images and files as well as app data, probably not needed to do both.
Alternatively, use ctrl + F5 to force a refresh should work.


# Proposed solution

Perhaps you can disable caching for user.js files.

The biggest issue for me is that this is quite confusing, seemingly unpredictable behaviour. It took writing this bug report to figure out just how I can continue developing an extension when updates didn't seem to work :)
Thanks for your work and let me know if you need more information!

**Comment by derjanb** [comment]
TM now should not cache neither scripts nor updates -> http://tampermonkey.net/changelog.php?version=4.0.5005&ext=gcal

Thanks a lot for this detailed bug report. :)

**Comment by svArtist** [comment]
The issue still exists on 4.5
Specifically: Visiting a script URL (e.g. GitHub Raw) on Chrome - is there a way to always manually request the content, bypassing any browser/system cache?
